version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 2.11.0
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: lodash-es
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
